# Generated by Django 3.2.2 on 2025-12-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StepAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('produce_close', models.BooleanField(default=False)),
                ('close_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='LeadFunnelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('closed', 'Cerrado')], default='active', max_length=20)),
                ('used_actions', models.JSONField(blank=True, default=list)),
                ('discarded_actions', models.JSONField(blank=True, default=list)),
                ('current_pool', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_states', to='funnels.step')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_states', to='funnels.funnel')),
                ('lead_full', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_states', to='main.leadfull')),
                ('suggested_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_in_states', to='funnels.stepaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StepActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(choices=[('once', 'Appear once'), ('until_used', 'Until used'), ('always', 'Always appear')], default='once', max_length=20)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnels.stepaction')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnels.step')),
            ],
            options={
                'ordering': ['action__priority'],
                'unique_together': {('step', 'action')},
            },
        ),
        migrations.CreateModel(
            name='MsgTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='funnels.funnel')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='funnels.step')),
                ('step_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='funnels.stepaction')),
            ],
            options={
                'ordering': ['slug'],
                'unique_together': {('slug', 'funnel')},
            },
        ),
    ]
