# Generated by Django 3.2.2 on 2025-12-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadfunnelstate',
            old_name='lead_full',
            new_name='lead',
        ),
    ]
