# Generated by Django 3.2.2 on 2025-12-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0002_rename_lead_full_leadfunnelstate_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfunnelstate',
            name='mock_message',
            field=models.TextField(blank=True, help_text='TEMPORAL - MOCK', null=True),
        ),
    ]
