# Generated by Django 3.2.2 on 2025-12-10 22:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_type', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('contacted', models.IntegerField(default=0)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('website_status', models.CharField(blank=True, max_length=200, null=True)),
                ('website_type', models.CharField(blank=True, max_length=200, null=True)),
                ('search_tag', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('phone_type', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('contacted', models.IntegerField(default=0)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('website_type', models.CharField(blank=True, max_length=200, null=True)),
                ('website_status', models.CharField(blank=True, max_length=200, null=True)),
                ('search_tag', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeadFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('street_address', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_type', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator()])),
                ('whatsapp_url', models.CharField(blank=True, max_length=500, null=True)),
                ('website_type', models.CharField(blank=True, max_length=200, null=True)),
                ('website_status', models.CharField(blank=True, max_length=200, null=True)),
                ('redes_sociales', models.JSONField(blank=True, null=True)),
                ('detalle_url', models.CharField(blank=True, max_length=500, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('rubros', models.JSONField(blank=True, null=True)),
                ('tiendas', models.JSONField(blank=True, null=True)),
                ('intents', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('SSL', 'SSL'), ('DOWN', 'Down / Caída'), ('TIMEOUT', 'Timeout')], default='DOWN', max_length=20)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('ssl_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('ssl_issue_type', models.CharField(blank=True, max_length=200, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('days_left', models.IntegerField(blank=True, null=True)),
                ('final_url', models.CharField(blank=True, max_length=500, null=True)),
                ('down_detected_at', models.DateTimeField(blank=True, null=True)),
                ('down_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('timeout_seconds', models.FloatField(blank=True, null=True)),
                ('timeout_url', models.CharField(blank=True, max_length=500, null=True)),
                ('stack_detectado', models.JSONField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='main.leadfull')),
            ],
        ),
    ]
