# Generated by Django 5.2.12 on 2026-03-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticotecnico',
            options={'ordering': ['id'], 'verbose_name': 'Diagnostico PDF'},
        ),
        migrations.AlterModelOptions(
            name='leadfull',
            options={'ordering': ['id'], 'verbose_name': 'Lead'},
        ),
    ]
