# Generated by Django 3.1.6 on 2022-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='prefix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dato',
            name='sufix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
