# Generated by Django 3.1.6 on 2022-04-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220426_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='phone_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
