# Generated by Django 3.1.6 on 2022-04-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='contacted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacted',
            field=models.IntegerField(default=0),
        ),
    ]
