# Generated by Django 3.1.6 on 2022-04-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220429_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='search_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='search_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
