# Generated by Django 3.1.6 on 2022-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220429_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
