# Generated by Django 3.1.6 on 2022-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220429_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='website_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
