# Generated by Django 3.1.6 on 2022-05-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220429_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='website_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
