# Generated by Django 5.2.12 on 2026-03-20 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('function_name', models.CharField(choices=[('send_message', 'send_message'), ('send_email', 'send_email'), ('send_whatsapp', 'send_whatsapp'), ('create_task', 'create_task'), ('notify_user', 'notify_user'), ('update_lead_status', 'update_lead_status'), ('follow_up', 'follow_up')], help_text='Función registrada en functions.py', max_length=100)),
                ('channel', models.CharField(blank=True, choices=[('WHATSAPP', '📱 WhatsApp'), ('EMAIL', '📧 Email'), ('CALL', '📞 Llamada')], help_text='Canal asociado a la acción', max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Config - Tipo de Acción',
                'verbose_name_plural': 'ActionTypes',
            },
        ),
        migrations.CreateModel(
            name='EventTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('STATUS', 'Status'), ('INTENT', 'Intent'), ('REPLY', 'Reply'), ('CONTEXT', 'Context / Microacciones'), ('LIFECYCLE', 'Lifecycle'), ('STRATEGY', 'Strategy / Scoring'), ('TIME', 'Temporal / Triggers'), ('MISC', 'Otros / Microeventos'), ('OTHER', 'Otro')], default='OTHER', help_text='Categoría del evento para filtros y dashboard', max_length=20)),
                ('should_alert', models.BooleanField(default=False)),
                ('alert_priority', models.IntegerField(default=5)),
                ('alert_title_template', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata_template', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Si el evento está habilitado')),
                ('allowed_auto', models.BooleanField(default=True, help_text='Puede ser disparado automáticamente')),
                ('unique_per_lead', models.BooleanField(default=True, help_text='Solo puede existir una vez por lead')),
                ('max_consumes', models.IntegerField(default=1, help_text='Cantidad máxima de consumos permitidos por lead')),
                ('ttl_hours', models.IntegerField(blank=True, help_text='Tiempo en horas que el evento es válido', null=True)),
            ],
            options={
                'verbose_name': 'Config - Tipo de Evento',
                'verbose_name_plural': 'EventTypes',
            },
        ),
        migrations.CreateModel(
            name='MatrixButtonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Slug de Lucide o FontAwesome (ej: dollar-sign, cpu)', max_length=50)),
                ('flavor', models.CharField(help_text="Define la variante del evento. Ej: 'not_owner' en 'intent_validation'.", max_length=50)),
                ('next_stage', models.CharField(choices=[('VALIDATION', 'Validation'), ('PAIN', 'Pain / Offer'), ('CALL', 'Call / Meeting'), ('CLOSED', 'Closed')], help_text='A qué etapa salta el Lead al presionar este botón.', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.eventtypeconfig')),
            ],
            options={
                'verbose_name': 'Estrategia - Botón de Matrix',
            },
        ),
        migrations.CreateModel(
            name='MatrixScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('VALIDATION', 'Validation'), ('PAIN', 'Pain / Offer'), ('CALL', 'Call / Meeting'), ('CLOSED', 'Closed')], max_length=20)),
                ('last_intent_slug', models.CharField(blank=True, db_index=True, help_text='El slug del botón previo que activa este tablero. Si es nulo, es el inicio de etapa.', max_length=100, null=True)),
                ('slot_adv_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_adv1', to='engine.matrixbuttonconfig')),
                ('slot_adv_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_adv2', to='engine.matrixbuttonconfig')),
                ('slot_adv_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_adv3', to='engine.matrixbuttonconfig')),
                ('slot_out_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_out1', to='engine.matrixbuttonconfig')),
                ('slot_out_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_out2', to='engine.matrixbuttonconfig')),
                ('slot_out_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_out3', to='engine.matrixbuttonconfig')),
                ('slot_sta_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_sta1', to='engine.matrixbuttonconfig')),
                ('slot_sta_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_sta2', to='engine.matrixbuttonconfig')),
                ('slot_sta_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_sta3', to='engine.matrixbuttonconfig')),
            ],
            options={
                'verbose_name': 'Estrategia - Escenario de Matrix',
            },
        ),
        migrations.CreateModel(
            name='MsgTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Debe coincidir con el slug del EventTypeConfig', max_length=100)),
                ('channel', models.CharField(choices=[('WHATSAPP', '📱 WhatsApp'), ('EMAIL', '📧 Email'), ('CALL', '📞 Llamada')], max_length=20)),
                ('segment', models.CharField(blank=True, choices=[('CORES', 'Cores (Optimizable)'), ('DOWN', 'Down (Web Caída)'), ('NO_CORES', 'No Cores (Infra Débil)'), ('SOCIAL', 'Social (Solo Redes)'), ('SSL_ERROR', 'SSL Error (Inseguro)'), ('TIMEOUT', 'Timeout (Lenta)')], help_text='Debe coincidir con el website_status del Lead', max_length=20, null=True)),
                ('subject', models.CharField(blank=True, help_text='Asunto (opcional, para Email)', max_length=255, null=True)),
                ('content', models.TextField(help_text='Contenido del mensaje. Soporta tags: {name}, {company}, etc.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Config - Plantilla',
                'verbose_name_plural': 'Templates',
                'unique_together': {('slug', 'segment', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='TriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual Only'), ('BOTH', 'Auto + Manual')], default='AUTO', max_length=10)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('payload_template', models.JSONField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('max_runs', models.IntegerField(blank=True, null=True)),
                ('cooldown_minutes', models.IntegerField(blank=True, null=True)),
                ('should_alert', models.BooleanField(default=False)),
                ('stop_processing', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('action_to_trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='engine.actiontypeconfig')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='engine.eventtypeconfig')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_rules', to='engine.msgtemplate')),
            ],
            options={
                'verbose_name': 'Config - Regla de Trigger',
                'verbose_name_plural': 'Triggers',
                'ordering': ['-priority'],
            },
        ),
    ]
