# Generated by Django 5.2.12 on 2026-03-20 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
        ('main', '0002_alter_diagnosticotecnico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leadfull')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, choices=[('WHATSAPP', '📱 WhatsApp'), ('EMAIL', '📧 Email'), ('CALL', '📞 Llamada')], max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(default=False)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.eventtypeconfig')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.leadfull')),
            ],
        ),
        migrations.CreateModel(
            name='LeadProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('interest', models.BooleanField(default=False)),
                ('capacity', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('call', models.BooleanField(default=False)),
                ('meet', models.BooleanField(default=False)),
                ('quote', models.BooleanField(default=False)),
                ('contract', models.BooleanField(default=False)),
                ('milestones_context', models.JSONField(blank=True, default=dict)),
                ('current_stage', models.CharField(db_index=True, default='VALIDATION', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('LOST', 'Lost'), ('WON', 'Won')], default='NEW', max_length=20)),
                ('next_followup_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_progress', to='sales.event')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='main.leadfull')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.leadfull')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_channel', models.CharField(choices=[('WHATSAPP', '📱 WhatsApp'), ('EMAIL', '📧 Email'), ('CALL', '📞 Llamada')], max_length=20, null=True)),
                ('mode', models.CharField(choices=[('AUTO', 'Automática (System)'), ('HUMAN', 'Manual (User)')], default='AUTO', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('execute_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.actiontypeconfig')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='sales.event')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.leadfull')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.msgtemplate')),
                ('trigger_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='engine.triggerrule')),
            ],
            options={
                'ordering': ['execute_at'],
            },
        ),
    ]
